### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

### ISSUE THREAD

**Issue by arbaleast** [jiangnianshun/django-mdict#8]
```shell
[MANAGE] manage path: /code/manage.py
[MYSITE.SETTINGS] settings path: /code/mysite/settings.py
[MDICT_UTILS.SET_MDICT_PATH] /code/media/mdict/doc is root dir.
[INIT_UTILS.CHECK_DIR_CHANGE] dir change founded.
Traceback (most recent call last):
  File "/code/manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.9/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/usr/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python3.9/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/code/mdict/apps.py", line 47, in ready
    init_mdict_list()
  File "/code/mdict/mdict_utils/init_utils.py", line 212, in init_mdict_list
    rewrite_cache(mdict_root_path)
  File "/code/mdict/mdict_utils/init_utils.py", line 195, in rewrite_cache
    init_vars.mdict_odict, init_vars.zim_list = get_mdict_dict(tmdict_root_path)
  File "/code/mdict/mdict_utils/mdict_utils2.py", line 70, in get_mdict_dict
    zim = ZIMFile(zim_path, encoding='utf-8')
  File "/code/mdict/readlib/src/readzim.py", line 396, in __init__
    self.header = self.metadata(zim_file)
  File "/code/mdict/readlib/src/readzim.py", line 716, in metadata
    return self.get_metadata_by_url(file)
  File "/code/mdict/readlib/src/readzim.py", line 698, in get_metadata_by_url
    metadata_dict.update({entry['url']: self._get_article_by_index(file, idx)[0].decode('utf-8')})
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte


```

**Comment by arbaleast** [comment]
在docker中部署，怀疑zim格式损坏，重下zim文件，还是一样的问题
```shell
wiki ➤ sudo docker version
[sudo] password for al:
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:07:51 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:07:51 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.26
  GitCommit:        3dd1e886e55dd695541fdcd67420c2888645a495
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by arbaleast** [comment]
默认是解析英文维基，[django-mdict](https://github.com/jiangnianshun/django-mdict/tree/master)/[mdict](https://github.com/jiangnianshun/django-mdict/tree/master/mdict)/[readlib](https://github.com/jiangnianshun/django-mdict/tree/master/mdict/readlib)/[src](https://github.com/jiangnianshun/django-mdict/tree/master/mdict/readlib/src/readzim.py)
更改编码为ISO-8859-1不知道能不能解决

**Comment by jiangnianshun** [comment]
你好，旧版wiki zim的url里只有文本，wikipedia_en_all_maxi_2023-08.zim里多了图片，导致解析失败。请把文件django-mdict\mdict\readlib\src\readzim.py更新为最新版本再试一下。
